/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.Conexion;
import clases.NuevoInicioSesion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JMenuBar.*;

/**
 *
 * @author Roberto Mendoza
 */
public class Login extends javax.swing.JFrame {

    //Conexion a la base de datos para buscar los usuarios
    Conexion conexion = new Conexion();
    Connection con = null;
    //Variable para ejectutar una consulta a la base de datos
    PreparedStatement ps;
    //Variable para almacenar el resultado de la consulta
    ResultSet res;

    //Almacenaje de 
    public String usuarioInicioSesion;//no es necesario
//
//    public String getUsuarioInicioSesion() {
//        return usuarioInicioSesion;
//    }

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //Relaizar conexion a BD
        con = conexion.getConexion();
        //Mostrar estado de conexion a bd
        //JOptionPane.showMessageDialog(null,conexion.getEstadoConexion());
        //lblEstadoConexion.setText(conexion.getEstadoConexion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigoUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtCodigoUsuario = new javax.swing.JTextField();
        lblPEMA = new javax.swing.JLabel();
        lblIngreseCredenciales = new javax.swing.JLabel();
        btnIniciarSesion_Login = new javax.swing.JButton();
        btnSalir_Login = new javax.swing.JButton();
        pwContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");

        lblCodigoUsuario.setText("Codigo de Usuario");

        lblContraseña.setText("Contraseña");

        lblPEMA.setText("SISTEMA DE GESTION DEL AREA DE PERECEDEROS ");

        lblIngreseCredenciales.setText("PEMA");

        btnIniciarSesion_Login.setText("Iniciar sesión");
        btnIniciarSesion_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesion_LoginActionPerformed(evt);
            }
        });

        btnSalir_Login.setText("Salir");
        btnSalir_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir_LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblPEMA)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIniciarSesion_Login)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigoUsuario)
                                    .addComponent(lblContraseña))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigoUsuario)
                                    .addComponent(pwContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblIngreseCredenciales)))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPEMA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIngreseCredenciales, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoUsuario)
                    .addComponent(txtCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña)
                    .addComponent(pwContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarSesion_Login)
                    .addComponent(btnSalir_Login))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalir_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir_LoginActionPerformed
        //Salir de la ejecución del programa
        System.exit(0);

    }//GEN-LAST:event_btnSalir_LoginActionPerformed

    private void btnIniciarSesion_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesion_LoginActionPerformed
        // Almacenar en las siguientes variables los datos ingresados
        String codigoUsuario = txtCodigoUsuario.getText();
        String contraseña = new String(pwContraseña.getPassword());
        String estado;
        /*Validar que ninguno de ambos campos queden vacíos, 
        indicandole al usuario*/
        if (((codigoUsuario.isEmpty()) || (contraseña.isEmpty()))) {
            JOptionPane.showMessageDialog(null, "No dejar campos vacíos");
        } else {
            if (("admin".equals(codigoUsuario)) && ("admin".equals(contraseña))) {
                //Instanciamos una clase que almacene el usuario que iniciara sesión
                NuevoInicioSesion nuevoInicioSesion = new NuevoInicioSesion(codigoUsuario, contraseña);
                //Cierra la ventana de inicio de sesion actual
                this.setVisible(false);
                //Instancia de la clase MenuPrincipal que accederá el Administrador
                MenuPrincipal menu = new MenuPrincipal();
                menu.setVisible(true);

            } else {
                try {
                    String tbUsuariosCodigoUsuario;
                    String tbUsuariosContraseñaUsuario;
                    String tbUsuariosEstadoUsuario;
                    String tbUsuariosCargo;
                    //Buscar usuario en tabla y validar, si no existe mostrar mensjase
                    //Ejecutar la consulta en tabla tb_usuarios de la BD
                    ps = con.prepareStatement("SELECT * FROM tb_usuarios WHERE codigoUsuario=?");
                    ps.setString(1, codigoUsuario);
                    res = ps.executeQuery();
                    //Validar si la consulta tiene resultados
                    if (res.next()) {
                        tbUsuariosCodigoUsuario = res.getString("codigoUsuario");
                        tbUsuariosContraseñaUsuario = res.getString("contraseña");
                        tbUsuariosEstadoUsuario = res.getString("estado");
                        tbUsuariosCargo = res.getString("cargo");
                        //Validar si el usuario ha digitado correctamente sus credenciales
                        //y si esta habilitado para ingresar al sistema
                        if ((tbUsuariosCodigoUsuario.equals(codigoUsuario)) && (tbUsuariosContraseñaUsuario.equals(contraseña)) && ("Habilitado".equals(tbUsuariosEstadoUsuario))) {
                            if ("Bodeguero".equals(tbUsuariosCargo)) {
                                MenuPrincipalBodeguero menu = new MenuPrincipalBodeguero();
                                this.setVisible(false);
                                menu.setVisible(true);
                            } else {
                                if ("Vendedor".equals(tbUsuariosCargo)) {
                                    JOptionPane.showMessageDialog(null, "Este menu aún está en mantenimiento");
                                } else {
                                    //Sino es vendedor ni bodeguero debe ser supervisor
                                    //Aún no hay menú para este tipo de usuario
                                    JOptionPane.showMessageDialog(null, "Este menu aún está en mantenimiento");
                                    txtCodigoUsuario.setText("");
                                    pwContraseña.setText("");
                                }
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Datos incorrectos o ha sido"
                                    + " deshabilitado del sistema, comuniquese con el administrador");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Usuario no registrado");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                txtCodigoUsuario.setText("");
                pwContraseña.setText("");
            }
        }
    }//GEN-LAST:event_btnIniciarSesion_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion_Login;
    private javax.swing.JButton btnSalir_Login;
    private javax.swing.JLabel lblCodigoUsuario;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblIngreseCredenciales;
    private javax.swing.JLabel lblPEMA;
    private javax.swing.JPasswordField pwContraseña;
    private javax.swing.JTextField txtCodigoUsuario;
    // End of variables declaration//GEN-END:variables
}
