/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author Roberto Mendoza
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mArc = new javax.swing.JMenu();
        mArc_inicioSesion = new javax.swing.JMenuItem();
        mArc_cerrarTodo = new javax.swing.JMenuItem();
        mArc_salir = new javax.swing.JMenuItem();
        mAdm = new javax.swing.JMenu();
        mAdm_agregarUsuario = new javax.swing.JMenuItem();
        mArc_editarUsuario = new javax.swing.JMenuItem();
        mInv = new javax.swing.JMenu();
        mInv_crearProd = new javax.swing.JMenuItem();
        mInv_ingresarProd = new javax.swing.JMenuItem();
        mInv_editarProd = new javax.swing.JMenuItem();
        mInv_dspacharProd = new javax.swing.JMenuItem();
        mInv_verificarInv = new javax.swing.JMenuItem();
        mV = new javax.swing.JMenu();
        mV_realizarV = new javax.swing.JMenuItem();
        mV_solicitarProd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        mArc.setText("Archivo");

        mArc_inicioSesion.setText("Iniciar sesion");
        mArc.add(mArc_inicioSesion);

        mArc_cerrarTodo.setText("Cerrar todo");
        mArc.add(mArc_cerrarTodo);

        mArc_salir.setText("Salir");
        mArc.add(mArc_salir);

        menuBar.add(mArc);

        mAdm.setText("Administración");

        mAdm_agregarUsuario.setText("Agregar usuario");
        mAdm.add(mAdm_agregarUsuario);

        mArc_editarUsuario.setText("Editar usuario");
        mAdm.add(mArc_editarUsuario);

        menuBar.add(mAdm);

        mInv.setText("Inventario");

        mInv_crearProd.setText("Crear producto");
        mInv.add(mInv_crearProd);

        mInv_ingresarProd.setText("Ingresar productos");
        mInv.add(mInv_ingresarProd);

        mInv_editarProd.setText("Editar producto");
        mInv.add(mInv_editarProd);

        mInv_dspacharProd.setText("Despachar prodcuto");
        mInv.add(mInv_dspacharProd);

        mInv_verificarInv.setText("Verificar Inventario");
        mInv.add(mInv_verificarInv);

        menuBar.add(mInv);

        mV.setText("Ventas");

        mV_realizarV.setText("Realizar venta");
        mV.add(mV_realizarV);

        mV_solicitarProd.setText("Solicitar productos");
        mV.add(mV_solicitarProd);

        menuBar.add(mV);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu mAdm;
    private javax.swing.JMenuItem mAdm_agregarUsuario;
    private javax.swing.JMenu mArc;
    private javax.swing.JMenuItem mArc_cerrarTodo;
    private javax.swing.JMenuItem mArc_editarUsuario;
    private javax.swing.JMenuItem mArc_inicioSesion;
    private javax.swing.JMenuItem mArc_salir;
    private javax.swing.JMenu mInv;
    private javax.swing.JMenuItem mInv_crearProd;
    private javax.swing.JMenuItem mInv_dspacharProd;
    private javax.swing.JMenuItem mInv_editarProd;
    private javax.swing.JMenuItem mInv_ingresarProd;
    private javax.swing.JMenuItem mInv_verificarInv;
    private javax.swing.JMenu mV;
    private javax.swing.JMenuItem mV_realizarV;
    private javax.swing.JMenuItem mV_solicitarProd;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
